name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t simple-fast-py-api .
      - name: Run app
        run: |
          docker run -d -p 8000:8000 -v $(pwd)/users.db:/app/users.db simple-fast-py-api
      # Sample requests
      - name: request-1
        run: |
          curl http://localhost:8000/users/ -H "Accept: application/json"
      - name: request-2
        run: |
          curl http://localhost:8000/users/1 -H "Accept: application/json"
